---
- name: Install K8S master services
  hosts: all
  tasks:
    - name: General | Load varibles
      include_vars:
        file: vars.yml

    - name: K8S | Install Master | Initialize K8S with kubeadm
      shell: kubeadm init --token={{ kubeadm_token }} --apiserver-advertise-address={{ k8s_master_ip }} --pod-network-cidr=192.168.10.0/24
      become: true
      become_method: sudo

    - name: K8S | Install Master | Create .kube directory
      file:
        path: "{{ lookup('env','HOME') }}/.kube"
        state: directory

    - name: K8S | Install Master | Copy admin.conf file to /.kube/config
      shell: "cp -i /etc/kubernetes/admin.conf {{ lookup('env','HOME') }}/.kube/config"
      become: true
      become_method: sudo

    - name: K8S | Install Master | Change ownership on /.kube/config
      file:
        path: "{{ lookup('env','HOME') }}/.kube/config"
        owner: vagrant
        group: vagrant
      become: true
      become_method: sudo

    - name: K8S | Install Master | Install pod network
      shell: kubectl apply -f http://docs.projectcalico.org/v2.4/getting-started/kubernetes/installation/hosted/kubeadm/1.6/calico.yaml
